POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "My Trip to Seoul",
    "author": "Andres Genda",
    "url": "https://mywebpage.com/triptoseoul",
    "likes": 50000
}