POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Night Out with Friends",
    "author": "Belly Conklin",
    "url": "https://mywebpage.com/nightoutwithfriends",
    "likes": 2000
}