POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Broccoli Soup Recipe",
    "author": "Andres Genda",
    "url": "https://mywebpage.com/broccolisoup",
    "likes": 5000
}