GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/ayo

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Mo",
    "number": "12-345-67890"
}

###

DELETE http://localhost:3001/api/persons/6892a955430603f1f1bc2bdf

###

PUT http://localhost:3001/api/persons/6892d39a0721c285cea547f5
Content-Type: application/json

{
    "name": "Ava Daniels",
    "number": "12-345-67891"
}